### ISSUE TITLE
remove_all_pyc Bug

### ISSUE THREAD

**Issue by juancarlospaco** [realpython/python-scripts#1]
https://github.com/realpython/python-scripts/blob/master/01_remove_all_pyc.md

All the Python 2 and 3 comes builtin with a battery to do that in a better way...
```
pyclean .
```

You can also make it more Verbose or use a path to a project or module or whatever like:
```
pyclean --verbose /home/code/foo/
```
This solution is Cross-platform and more safe.

And the proposed solution on 01_remove_all_pyc.md will Fail to clean `*.pyo` and `*.pyd`.

**Comment by mjhea0** [comment]
I'm pretty sure `pyclean` is ubuntu only
